In [1]:
import os
import pandas as pd
import numpy as np
import yfinance as yf

In [2]:
try:
    os.mkdir("out")
    print("directory created")
except FileExistsError:
    print("out folder already exists")
except OSError as e:
    print(f"error creating out folder: {e}")

directory created

In [3]:
tickers_csv = os.path.join("out", "tickers.csv")
tickers = ["AAPL","MSFT","GOOGL","AMZN","META","NVDA","AVGO","ORCL","IBM","SAP",
        "JPM","BAC","WFC","MS","GS","BLK","V","MA","BRK-B","KO",
        "PG","PEP","WMT","COST","HD","MCD","DIS","NKE","GE","UNH",
        "LLY","PFE","MRK","ABT","TMO","AMGN","ADBE","CRM","NOW","SNOW",
        "AMD","TSM","ASML","AMAT","TSLA","FSLR","ENPH","NEE","PLTR","PANW"]
pd.DataFrame({"ticker": tickers}).to_csv(tickers_csv, index=False)

In [4]:
# Date range for collecting stock price data (including the initial quarter lookback before portfolio creation)
# starts collecting data from April 1, 2024 with the period from April 1, 2024 to June 30, 2024 being used as the lookback
# to help portfolio allocation on July 1, 2024. Stays updated to the latest stock movements
start = "2024-04-01"
end = None

In [5]:
data = yf.download(tickers, start = start, end = end, auto_adjust = True)

[*********************100%***********************]  50 of 50 completed

In [6]:
prices = data["Close"]

In [7]:
prices = prices.dropna(how = "all").sort_index()
prices = prices.dropna(axis = 1, how = "any")

In [8]:
pct_returns = prices.pct_change().dropna()

In [9]:
prices

Ticker,AAPL,ABT,ADBE,AMAT,AMD,AMGN,AMZN,ASML,AVGO,BAC,...,PLTR,SAP,SNOW,TMO,TSLA,TSM,UNH,V,WFC,WMT
Date,,,,,,,,,,,,,,,,,,,,,
2024-04-01,168.817703,108.856194,502.089996,205.770752,183.339996,270.070251,180.970001,979.160461,133.081970,36.401070,...,22.860001,191.865738,160.520004,575.178833,175.220001,139.029495,478.594421,275.276886,55.609509,59.047344
2024-04-02,167.636185,108.788216,499.209991,203.226852,178.699997,263.553223,180.690002,953.284912,131.948547,36.187630,...,22.719999,188.038818,156.190002,569.312012,166.630005,137.781586,447.750153,275.435120,55.358536,58.220680
2024-04-03,168.440399,108.069550,497.010010,204.479095,180.770004,261.845245,182.410004,966.656555,134.358353,36.323456,...,22.700001,189.135025,153.020004,573.734558,168.380005,139.530624,449.313873,273.971069,55.146179,58.486397
2024-04-04,167.616333,106.933327,487.109985,200.544876,165.830002,255.805328,180.000000,940.169556,129.853149,35.818962,...,22.480000,186.971970,151.339996,568.365784,171.110001,137.231339,445.052734,271.043091,54.711803,58.555283
2024-04-05,168.370911,107.991867,485.119995,204.942505,170.419998,257.580139,185.070007,965.946594,132.014572,36.003296,...,22.959999,187.745193,153.860001,577.180908,164.899994,138.901749,445.404572,274.149200,55.406803,58.899727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-08-27,230.490005,131.460007,356.350006,164.389999,167.130005,287.970001,229.119995,770.000000,300.250000,50.380001,...,156.720001,275.109985,200.389999,488.119995,349.600006,239.289993,303.880005,350.350006,82.500000,96.080002
2025-08-28,232.559998,131.369995,353.959991,165.270004,168.580002,285.609985,231.600006,763.460022,308.649994,50.490002,...,158.119995,275.399994,241.000000,489.739990,345.980011,238.270004,302.290009,349.859985,81.980003,96.110001
2025-08-29,232.139999,132.660004,356.700012,160.759995,162.630005,287.709991,229.000000,742.619995,297.390015,50.740002,...,156.710007,272.160004,238.660004,492.720001,333.869995,230.869995,309.869995,351.779999,82.180000,96.980003
2025-09-02,229.720001,131.460007,345.630005,157.570007,162.320007,286.920013,225.339996,725.849976,298.239990,50.419998,...,157.089996,266.200012,233.600006,487.529999,329.359985,228.389999,308.799988,350.070007,81.779999,97.849998
2025-09-03,237.527405,130.434998,347.589996,154.949997,161.649994,283.429993,225.809998,736.609985,302.859985,49.980000,...,157.406097,269.734985,230.654999,483.480011,342.265015,231.050003,305.510010,348.410004,80.239998,98.775002

In [10]:
prices_out = prices.reset_index().rename(columns = {"Date": "Date"})
returns_out = pct_returns.reset_index().rename(columns = {"Date": "Date"})

In [11]:
prices_out

Ticker,Date,AAPL,ABT,ADBE,AMAT,AMD,AMGN,AMZN,ASML,AVGO,...,PLTR,SAP,SNOW,TMO,TSLA,TSM,UNH,V,WFC,WMT
0,2024-04-01,168.817703,108.856194,502.089996,205.770752,183.339996,270.070251,180.970001,979.160461,133.081970,...,22.860001,191.865738,160.520004,575.178833,175.220001,139.029495,478.594421,275.276886,55.609509,59.047344
1,2024-04-02,167.636185,108.788216,499.209991,203.226852,178.699997,263.553223,180.690002,953.284912,131.948547,...,22.719999,188.038818,156.190002,569.312012,166.630005,137.781586,447.750153,275.435120,55.358536,58.220680
2,2024-04-03,168.440399,108.069550,497.010010,204.479095,180.770004,261.845245,182.410004,966.656555,134.358353,...,22.700001,189.135025,153.020004,573.734558,168.380005,139.530624,449.313873,273.971069,55.146179,58.486397
3,2024-04-04,167.616333,106.933327,487.109985,200.544876,165.830002,255.805328,180.000000,940.169556,129.853149,...,22.480000,186.971970,151.339996,568.365784,171.110001,137.231339,445.052734,271.043091,54.711803,58.555283
4,2024-04-05,168.370911,107.991867,485.119995,204.942505,170.419998,257.580139,185.070007,965.946594,132.014572,...,22.959999,187.745193,153.860001,577.180908,164.899994,138.901749,445.404572,274.149200,55.406803,58.899727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,2025-08-27,230.490005,131.460007,356.350006,164.389999,167.130005,287.970001,229.119995,770.000000,300.250000,...,156.720001,275.109985,200.389999,488.119995,349.600006,239.289993,303.880005,350.350006,82.500000,96.080002
354,2025-08-28,232.559998,131.369995,353.959991,165.270004,168.580002,285.609985,231.600006,763.460022,308.649994,...,158.119995,275.399994,241.000000,489.739990,345.980011,238.270004,302.290009,349.859985,81.980003,96.110001
355,2025-08-29,232.139999,132.660004,356.700012,160.759995,162.630005,287.709991,229.000000,742.619995,297.390015,...,156.710007,272.160004,238.660004,492.720001,333.869995,230.869995,309.869995,351.779999,82.180000,96.980003
356,2025-09-02,229.720001,131.460007,345.630005,157.570007,162.320007,286.920013,225.339996,725.849976,298.239990,...,157.089996,266.200012,233.600006,487.529999,329.359985,228.389999,308.799988,350.070007,81.779999,97.849998
357,2025-09-03,237.527405,130.434998,347.589996,154.949997,161.649994,283.429993,225.809998,736.609985,302.859985,...,157.406097,269.734985,230.654999,483.480011,342.265015,231.050003,305.510010,348.410004,80.239998,98.775002

In [12]:
prices_out.to_csv("out/prices.csv", index=False)
returns_out.to_csv("out/returns.csv", index=False)